[build]
  command = "bundle config set force_ruby_platform true && bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.4.0"
  JEKYLL_ENV = "production"

[[plugins]]
  package = "netlify-plugin-jekyll-cache"
